In [30]:
import pandas as pd
import os
import datetime

In [31]:
file1 = "Resources/JC-202201-citibike-tripdata.csv"
file2 = "Resources/JC-202202-citibike-tripdata.csv"
file3 = "Resources/JC-202203-citibike-tripdata.csv"
file4 = "Resources/JC-202204-citibike-tripdata.csv"
file5 = "Resources/JC-202205-citibike-tripdata.csv"
file6 = "Resources/JC-202206-citibike-tripdata.csv"

file_list = [file1,file2,file3,file4,file5]
df_list = []

for file in file_list:
    df = pd.read_csv(file, encoding='utf-8', encoding_errors='replace')
    df_list.append(df)

print(df_list)

[                ride_id  rideable_type           started_at  \
0      CA5837152804D4B5  electric_bike  2022-01-26 18:50:39
1      BA06A5E45B6601D2   classic_bike  2022-01-28 13:14:07
2      7B6827D7B9508D93   classic_bike  2022-01-10 19:55:13
3      6E5864EA6FCEC90D  electric_bike  2022-01-26 07:54:57
4      E24954255BBDE32D  electric_bike  2022-01-13 18:44:46
...                 ...            ...                  ...
26757  439B3B4ADB37F46F  electric_bike  2022-01-03 16:07:27
26758  11C0F2F85CBF7623  electric_bike  2022-01-22 20:02:58
26759  E77502BB6C6A7ADD   classic_bike  2022-01-26 12:35:21
26760  75C57C18EE9980EA   classic_bike  2022-01-28 12:56:34
26761  2EC5621EF3DCB2FA   classic_bike  2022-01-31 12:45:16

                  ended_at    start_station_name start_station_id  \
0      2022-01-26 18:51:53  12 St & Sinatra Dr N            HB201
1      2022-01-28 13:20:23      Essex Light Rail            JC038
2      2022-01-10 20:00:37      Essex Light Rail            JC038
3      2022-01-26 07:55:22  12 St & Sinatra Dr N            HB201
4      2022-01-13 18:45:43  12 St & Sinatra Dr N            HB201
...                    ...                   ...              ...
26757  2022-01-03 16:12:05   Leonard Gordon Park            JC080
26758  2022-01-22 20:07:32   Leonard Gordon Park            JC080
26759  2022-01-26 12:44:00   Leonard Gordon Park            JC080
26760  2022-01-28 13:06:45   Leonard Gordon Park            JC080
26761  2022-01-31 12:52:05   Leonard Gordon Park            JC080

           end_station_name end_station_id  start_lat  start_lng    end_lat  \
0      12 St & Sinatra Dr N          HB201  40.750604 -74.024020  40.750604
1          Essex Light Rail          JC038  40.712774 -74.036486  40.712774
2          Essex Light Rail          JC038  40.712774 -74.036486  40.712774
3      12 St & Sinatra Dr N          HB201  40.750604 -74.024020  40.750604
4      12 St & Sinatra Dr N          HB201  40.750604 -74.024020  40.750604
...                     ...            ...        ...        ...        ...
26757        Journal Square          JC103  40.745910 -74.057271  40.733670
26758        Journal Square          JC103  40.745910 -74.057271  40.733670
26759        Journal Square          JC103  40.745910 -74.057271  40.733670
26760        Journal Square          JC103  40.745910 -74.057271  40.733670
26761        Journal Square          JC103  40.745910 -74.057271  40.733670

         end_lng member_casual
0     -74.024020        member
1     -74.036486        member
2     -74.036486        member
3     -74.024020        member
4     -74.024020        member
...          ...           ...
26757 -74.062500        member
26758 -74.062500        member
26759 -74.062500        member
26760 -74.062500        member
26761 -74.062500        member

[26762 rows x 13 columns],                 ride_id  rideable_type           started_at  \
0      B7BCBC133222B04A   classic_bike  2022-02-17 11:48:16
1      0F9F1A0F18FD3A22  electric_bike  2022-02-02 08:31:26
2      44B5D106DDB509AC  electric_bike  2022-02-09 14:05:49
3      E1434F258C195DC6   classic_bike  2022-02-08 07:57:44
4      64821879B2659E35   classic_bike  2022-02-07 08:05:28
...                 ...            ...                  ...
31906  56F2CE737BC48B4F  electric_bike  2022-02-26 22:56:54
31907  B9123C9BA1E8A1E0  electric_bike  2022-02-26 22:53:08
31908  93421FA350A599A4  electric_bike  2022-02-22 12:38:05
31909  92EA21949B94DBE4   classic_bike  2022-02-16 19:20:25
31910  BBD984693E611685   classic_bike  2022-02-21 09:36:56

                  ended_at       start_station_name start_station_id  \
0      2022-02-17 11:58:30              Astor Place            JC077
1      2022-02-02 08:38:08              Astor Place            JC077
2      2022-02-09 14:10:21              Astor Place            JC077
3      2022-02-08 08:15:26              Astor Place            JC077
4      2022-02-07 08:24:03              Astor Place            JC077
...                    ...                      ...              ...
31906  2022-02-26 23:43:17  Bergen Ave & Stegman St            JC108
31907  2022-02-26 23:43:19  Bergen Ave & Stegman St            JC108
31908  2022-02-22 13:22:14  Bergen Ave & Stegman St            JC108
31909  2022-02-17 12:31:04  Bergen Ave & Stegman St            JC108
31910  2022-02-21 10:24:35  Bergen Ave & Stegman St            JC108

              end_station_name end_station_id  start_lat  start_lng  \
0               Journal Square          JC103  40.719282 -74.071262
1                      Sip Ave          JC056  40.719282 -74.071262
2                      Sip Ave          JC056  40.719282 -74.071262
3                      Sip Ave          JC056  40.719282 -74.071262
4                      Sip Ave          JC056  40.719282 -74.071262
...                        ...            ...        ...        ...
31906  Bergen Ave & Stegman St          JC108  40.706575 -74.086701
31907  Bergen Ave & Stegman St          JC108  40.706575 -74.086701
31908  Bergen Ave & Stegman St          JC108  40.706575 -74.086701
31909  Bergen Ave & Stegman St          JC108  40.706575 -74.086701
31910        JC Medical Center          JC011  40.706575 -74.086701

         end_lat    end_lng member_casual
0      40.733670 -74.062500        member
1      40.730897 -74.063913        member
2      40.730897 -74.063913        member
3      40.730897 -74.063913        member
4      40.730897 -74.063913        member
...          ...        ...           ...
31906  40.706575 -74.086701        casual
31907  40.706575 -74.086701        casual
31908  40.706575 -74.086701        casual
31909  40.706575 -74.086701        casual
31910  40.716540 -74.049638        member

[31911 rows x 13 columns],                 ride_id  rideable_type           started_at  \
0      3255D3E3F33CDC45   classic_bike  2022-03-18 15:38:17
1      17FA5604A37338F9  electric_bike  2022-03-04 16:44:48
2      7DEC9ADDB8D6BBE1  electric_bike  2022-03-13 17:44:32
3      9D69F74EEF231A2E   classic_bike  2022-03-13 15:33:47
4      C84AE4A9D78A6347   classic_bike  2022-03-11 12:21:18
...                 ...            ...                  ...
51666  3A7A3C110A3A3C88  electric_bike  2022-03-03 16:47:15
51667  36C8F4EE77F2FDD2   classic_bike  2022-03-08 18:02:08
51668  B5F6267C3AA0B056   classic_bike  2022-03-07 18:54:55
51669  96A4FDC378B5E764   classic_bike  2022-03-19 02:58:42
51670  225672DF871455F8  electric_bike  2022-03-30 14:15:47

                  ended_at                      start_station_name  \
0      2022-03-18 15:45:34  Mama Johnson Field - 4 St & Jackson St
1      2022-03-04 16:50:45                   Baldwin at Montgomery
2      2022-03-13 17:54:44                   Baldwin at Montgomery
3      2022-03-13 15:41:22                   Baldwin at Montgomery
4      2022-03-11 12:33:24                   Baldwin at Montgomery
...                    ...                                     ...
51666  2022-03-03 16:51:28                      Willow Ave & 12 St
51667  2022-03-08 18:14:41                      Willow Ave & 12 St
51668  2022-03-07 19:07:06                      Willow Ave & 12 St
51669  2022-03-19 03:14:37                      Willow Ave & 12 St
51670  2022-03-30 14:20:11                      Willow Ave & 12 St

      start_station_id                              end_station_name  \
0                HB404  South Waterfront Walkway - Sinatra Dr & 1 St
1                JC020                                 Grove St PATH
2                JC020                                 Grove St PATH
3                JC020                                 Grove St PATH
4                JC020                                 Grove St PATH
...                ...                                           ...
51666            HB505                 9 St HBLR - Jackson St & 8 St
51667            HB505                                 Washington St
51668            HB505                                 Washington St
51669            HB505                                 Washington St
51670            HB505                 9 St HBLR - Jackson St & 8 St

      end_station_id  start_lat  start_lng    end_lat    end_lng member_casual
0              HB103  40.743140 -74.040041  40.736982 -74.027781        casual
1              JC005  40.723659 -74.064194  40.719586 -74.043117        member
2              JC005  40.723659 -74.064194  40.719586 -74.043117        member
3              JC005  40.723659 -74.064194  40.719586 -74.043117        member
4              JC005  40.723659 -74.064194  40.719586 -74.043117        member
...              ...        ...        ...        ...        ...           ...
51666          HB305  40.751867 -74.030377  40.747907 -74.038412        member
51667          JC098  40.751867 -74.030377  40.724294 -74.035483        member
51668          JC098  40.751867 -74.030377  40.724294 -74.035483        member
51669          JC098  40.751867 -74.030377  40.724294 -74.035483        casual
51670          HB305  40.751867 -74.030377  40.747907 -74.038412        member

[51671 rows x 13 columns],                 ride_id  rideable_type           started_at  \
0      919C40A703A965D7  electric_bike  2022-04-15 15:02:20
1      3B40831921DAD6C1   classic_bike  2022-04-08 10:20:55
2      69C5C0766309F73D  electric_bike  2022-04-09 14:14:04
3      304B82055A1D4A24   classic_bike  2022-04-05 19:43:37
4      1CB760ECBCB08609   classic_bike  2022-04-17 11:25:26
...                 ...            ...                  ...
62523  13C1C453508F048A   classic_bike  2022-04-24 12:52:09
62524  B7E454B8886D7826  electric_bike  2022-04-30 11:45:56
62525  20D6A9E7C8291984   classic_bike  2022-04-28 14:28:34
62526  2AEB863A4F683CAE  electric_bike  2022-04-09 17:37:14
62527  AB2C885E7051B2D4   classic_bike  2022-04-02 15:54:12

                  ended_at                            start_station_name  \
0      2022-04-15 15:57:16                                Pershing Field
1      2022-04-08 10:25:29                             JC Medical Center
2      2022-04-09 14:18:51        Mama Johnson Field - 4 St & Jackson St
3      2022-04-05 19:51:14      Hoboken Terminal - Hudson St & Hudson Pl
4      2022-04-17 11:29:45        Mama Johnson Field - 4 St & Jackson St
...                    ...                                           ...
62523  2022-04-24 13:06:24  South Waterfront Walkway - Sinatra Dr & 1 St
62524  2022-04-30 11:54:30  South Waterfront Walkway - Sinatra Dr & 1 St
62525  2022-04-28 14:41:35  South Waterfront Walkway - Sinatra Dr & 1 St
62526  2022-04-09 17:46:45  South Waterfront Walkway - Sinatra Dr & 1 St
62527  2022-04-02 16:02:53  South Waterfront Walkway - Sinatra Dr & 1 St

      start_station_id                            end_station_name  \
0                JC024                              Pershing Field
1                JC011                                    Grand St
2                HB404  Southwest Park - Jackson St & Observer Hwy
3                HB101                          Marshall St & 2 St
4                HB404      Mama Johnson Field - 4 St & Jackson St
...                ...                                         ...
62523            HB103               9 St HBLR - Jackson St & 8 St
62524            HB103                        12 St & Sinatra Dr N
62525            HB103                       Bloomfield St & 15 St
62526            HB103                       Bloomfield St & 15 St
62527            HB103                           Clinton St & 7 St

      end_station_id  start_lat  start_lng    end_lat    end_lng member_casual
0              JC024  40.742677 -74.051789  40.742677 -74.051789        casual
1              JC102  40.716540 -74.049638  40.715178 -74.037683        member
2              HB401  40.743140 -74.040041  40.737551 -74.041664        member
3              HB408  40.735938 -74.030305  40.740802 -74.042521        casual
4              HB404  40.743140 -74.040041  40.743140 -74.040041        member
...              ...        ...        ...        ...        ...           ...
62523          HB305  40.736982 -74.027781  40.747907 -74.038412        member
62524          HB201  40.736982 -74.027781  40.750604 -74.024020        member
62525          HB203  40.736982 -74.027781  40.754530 -74.026580        member
62526          HB203  40.736982 -74.027781  40.754530 -74.026580        casual
62527          HB303  40.736982 -74.027781  40.745420 -74.033320        casual

[62528 rows x 13 columns],                 ride_id  rideable_type           started_at  \
0      FC9EB68D6501F079  electric_bike  2022-05-15 14:02:06
1      932A2D5E45ACED5B  electric_bike  2022-05-13 15:30:14
2      8C0CD371C7A5795C  electric_bike  2022-05-31 20:41:39
3      25BC1B079FBC71B9   classic_bike  2022-05-29 17:24:23
4      0B0F776B55C85AB8   classic_bike  2022-05-26 16:49:12
...                 ...            ...                  ...
80477  6099860AF8FAA526  electric_bike  2022-05-18 19:32:32
80478  47939F6BE837EA86  electric_bike  2022-05-23 17:30:23
80479  AB5BF7F1FDB1178D  electric_bike  2022-05-30 22:49:32
80480  D5CB837D520EA8DB  electric_bike  2022-05-18 22:52:08
80481  1CCC7CEC382DD1C0  electric_bike  2022-05-19 22:52:26

                  ended_at                        start_station_name  \
0      2022-05-15 14:05:44  Hoboken Terminal - Hudson St & Hudson Pl
1      2022-05-13 15:33:03  Hoboken Terminal - Hudson St & Hudson Pl
2      2022-05-31 22:04:47  Hoboken Terminal - Hudson St & Hudson Pl
3      2022-05-30 18:24:16  Hoboken Terminal - Hudson St & Hudson Pl
4      2022-05-26 16:57:01  Hoboken Terminal - Hudson St & Hudson Pl
...                    ...                                       ...
80477  2022-05-18 19:49:58                             Grove St PATH
80478  2022-05-23 17:49:30                          Marin Light Rail
80479  2022-05-30 23:09:59                                 Warren St
80480  2022-05-18 23:08:25                              Manila & 1st
80481  2022-05-19 23:10:51                              Manila & 1st

      start_station_id                              end_station_name  \
0                HB101                              Hudson St & 4 St
1                HB101                              Hudson St & 4 St
2                HB101  South Waterfront Walkway - Sinatra Dr & 1 St
3                HB101                                           NaN
4                HB101                    Hoboken Ave at Monmouth St
...                ...                                           ...
80477            JC005                       Bergen Ave & Stegman St
80478            JC013                       Bergen Ave & Stegman St
80479            JC006                       Bergen Ave & Stegman St
80480            JC082                       Bergen Ave & Stegman St
80481            JC082                       Bergen Ave & Stegman St

      end_station_id  start_lat  start_lng    end_lat    end_lng member_casual
0              HB607  40.735938 -74.030305  40.740973 -74.028603        member
1              HB607  40.735938 -74.030305  40.740973 -74.028603        casual
2              HB103  40.735938 -74.030305  40.736982 -74.027781        casual
3                NaN  40.735938 -74.030305        NaN        NaN        member
4              JC105  40.735938 -74.030305  40.735208 -74.046964        member
...              ...        ...        ...        ...        ...           ...
80477          JC108  40.719586 -74.043117  40.706575 -74.086701        casual
80478          JC108  40.714584 -74.042817  40.706575 -74.086701        member
80479          JC108  40.721124 -74.038051  40.706575 -74.086701        casual
80480          JC108  40.721651 -74.042884  40.706575 -74.086701        casual
80481          JC108  40.721651 -74.042884  40.706575 -74.086701        casual

[80482 rows x 13 columns]]

In [32]:
if os.path.exists(file6):
    print("file exists")
else:
    print("cant find it")

file exists

In [33]:
df_merged = pd.concat(df_list)
df_merged.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [34]:
df_merged.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [35]:
df_merged.isnull().sum()

ride_id                 0
rideable_type           0
started_at              0
ended_at                0
start_station_name      0
start_station_id        0
end_station_name      917
end_station_id        917
start_lat               0
start_lng               0
end_lat               628
end_lng               628
member_casual           0
dtype: int64

In [36]:
df_merged.shape

(253354, 13)

In [37]:
df_merged[['started_at', 'ended_at']] = df_merged[['started_at', 'ended_at']].apply(pd.to_datetime)
df_merged.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [38]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 253354 entries, 0 to 80481
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             253354 non-null  object
 1   rideable_type       253354 non-null  object
 2   started_at          253354 non-null  datetime64[ns]
 3   ended_at            253354 non-null  datetime64[ns]
 4   start_station_name  253354 non-null  object
 5   start_station_id    253354 non-null  object
 6   end_station_name    252437 non-null  object
 7   end_station_id      252437 non-null  object
 8   start_lat           253354 non-null  float64
 9   start_lng           253354 non-null  float64
 10  end_lat             252726 non-null  float64
 11  end_lng             252726 non-null  float64
 12  member_casual       253354 non-null  object
dtypes: datetime64[ns](2), float64(4), object(7)
memory usage: 27.1+ MB

In [39]:
df_merged.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
80477,6099860AF8FAA526,electric_bike,2022-05-18 19:32:32,2022-05-18 19:49:58,Grove St PATH,JC005,Bergen Ave & Stegman St,JC108,40.719586,-74.043117,40.706575,-74.086701,casual
80478,47939F6BE837EA86,electric_bike,2022-05-23 17:30:23,2022-05-23 17:49:30,Marin Light Rail,JC013,Bergen Ave & Stegman St,JC108,40.714584,-74.042817,40.706575,-74.086701,member
80479,AB5BF7F1FDB1178D,electric_bike,2022-05-30 22:49:32,2022-05-30 23:09:59,Warren St,JC006,Bergen Ave & Stegman St,JC108,40.721124,-74.038051,40.706575,-74.086701,casual
80480,D5CB837D520EA8DB,electric_bike,2022-05-18 22:52:08,2022-05-18 23:08:25,Manila & 1st,JC082,Bergen Ave & Stegman St,JC108,40.721651,-74.042884,40.706575,-74.086701,casual
80481,1CCC7CEC382DD1C0,electric_bike,2022-05-19 22:52:26,2022-05-19 23:10:51,Manila & 1st,JC082,Bergen Ave & Stegman St,JC108,40.721651,-74.042884,40.706575,-74.086701,casual

In [40]:
df_merged['ride_id'] = df_merged['ride_id'].astype('string')
df_merged.dtypes

ride_id                       string
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [41]:
df_merged[['rideable_type', 'start_station_name', 'end_station_name', 'member_casual']] = df_merged[['rideable_type', 'start_station_name', 'end_station_name', 'member_casual']].astype('string')
df_merged.dtypes

ride_id                       string
rideable_type                 string
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            string
start_station_id              object
end_station_name              string
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 string
dtype: object

In [42]:
df_merged.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [43]:
df_merged.tail(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
80477,6099860AF8FAA526,electric_bike,2022-05-18 19:32:32,2022-05-18 19:49:58,Grove St PATH,JC005,Bergen Ave & Stegman St,JC108,40.719586,-74.043117,40.706575,-74.086701,casual
80478,47939F6BE837EA86,electric_bike,2022-05-23 17:30:23,2022-05-23 17:49:30,Marin Light Rail,JC013,Bergen Ave & Stegman St,JC108,40.714584,-74.042817,40.706575,-74.086701,member
80479,AB5BF7F1FDB1178D,electric_bike,2022-05-30 22:49:32,2022-05-30 23:09:59,Warren St,JC006,Bergen Ave & Stegman St,JC108,40.721124,-74.038051,40.706575,-74.086701,casual
80480,D5CB837D520EA8DB,electric_bike,2022-05-18 22:52:08,2022-05-18 23:08:25,Manila & 1st,JC082,Bergen Ave & Stegman St,JC108,40.721651,-74.042884,40.706575,-74.086701,casual
80481,1CCC7CEC382DD1C0,electric_bike,2022-05-19 22:52:26,2022-05-19 23:10:51,Manila & 1st,JC082,Bergen Ave & Stegman St,JC108,40.721651,-74.042884,40.706575,-74.086701,casual

In [44]:
df_merged.shape

(253354, 13)

In [45]:
df.index[-1]

80481

In [46]:
num_rows = df.count()
num_rows

ride_id               80482
rideable_type         80482
started_at            80482
ended_at              80482
start_station_name    80482
start_station_id      80482
end_station_name      80296
end_station_id        80296
start_lat             80482
start_lng             80482
end_lat               80302
end_lng               80302
member_casual         80482
dtype: int64

In [47]:
df_merged = df_merged.drop_duplicates()
df_merged.shape

(253354, 13)

In [48]:
num_rows

ride_id               80482
rideable_type         80482
started_at            80482
ended_at              80482
start_station_name    80482
start_station_id      80482
end_station_name      80296
end_station_id        80296
start_lat             80482
start_lng             80482
end_lat               80302
end_lng               80302
member_casual         80482
dtype: int64

In [49]:
df_merged.isna().sum()

ride_id                 0
rideable_type           0
started_at              0
ended_at                0
start_station_name      0
start_station_id        0
end_station_name      917
end_station_id        917
start_lat               0
start_lng               0
end_lat               628
end_lng               628
member_casual           0
dtype: int64

In [50]:
df_merged.iloc[40000:50001].head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
13238,810134E785CC4C47,classic_bike,2022-02-17 18:07:12,2022-02-17 18:14:44,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13239,A93DBDFF6F0AD570,classic_bike,2022-02-16 21:20:00,2022-02-16 21:26:21,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13240,372ECD57A0BE6067,electric_bike,2022-02-15 19:39:23,2022-02-15 19:44:51,Hoboken Terminal - River St & Hudson Pl,HB102,11 St & Washington St,HB502,40.736068,-74.029127,40.749985,-74.027150,casual
13241,16C5D300AD089C3A,classic_bike,2022-02-26 21:25:30,2022-02-26 21:31:38,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13242,5CA2E46CA2579575,electric_bike,2022-02-02 20:41:17,2022-02-02 20:46:59,Hoboken Terminal - River St & Hudson Pl,HB102,11 St & Washington St,HB502,40.736068,-74.029127,40.749985,-74.027150,casual

In [51]:
df_merged['rideable_type'] = df_merged['rideable_type'].str.replace('_',' ')
df_merged.iloc[40000:50001].head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
13238,810134E785CC4C47,classic bike,2022-02-17 18:07:12,2022-02-17 18:14:44,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13239,A93DBDFF6F0AD570,classic bike,2022-02-16 21:20:00,2022-02-16 21:26:21,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13240,372ECD57A0BE6067,electric bike,2022-02-15 19:39:23,2022-02-15 19:44:51,Hoboken Terminal - River St & Hudson Pl,HB102,11 St & Washington St,HB502,40.736068,-74.029127,40.749985,-74.027150,casual
13241,16C5D300AD089C3A,classic bike,2022-02-26 21:25:30,2022-02-26 21:31:38,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13242,5CA2E46CA2579575,electric bike,2022-02-02 20:41:17,2022-02-02 20:46:59,Hoboken Terminal - River St & Hudson Pl,HB102,11 St & Washington St,HB502,40.736068,-74.029127,40.749985,-74.027150,casual

In [52]:
df_merged.rename(columns={col:col.replace("_"," ") for col in df_merged.columns if "_" in col }, inplace=True)
df_merged.iloc[40000:50001].head()

,ride id,rideable type,started at,ended at,start station name,start station id,end station name,end station id,start lat,start lng,end lat,end lng,member casual
13238,810134E785CC4C47,classic bike,2022-02-17 18:07:12,2022-02-17 18:14:44,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13239,A93DBDFF6F0AD570,classic bike,2022-02-16 21:20:00,2022-02-16 21:26:21,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13240,372ECD57A0BE6067,electric bike,2022-02-15 19:39:23,2022-02-15 19:44:51,Hoboken Terminal - River St & Hudson Pl,HB102,11 St & Washington St,HB502,40.736068,-74.029127,40.749985,-74.027150,casual
13241,16C5D300AD089C3A,classic bike,2022-02-26 21:25:30,2022-02-26 21:31:38,Hoboken Terminal - River St & Hudson Pl,HB102,8 St & Washington St,HB603,40.736068,-74.029127,40.745984,-74.028199,casual
13242,5CA2E46CA2579575,electric bike,2022-02-02 20:41:17,2022-02-02 20:46:59,Hoboken Terminal - River St & Hudson Pl,HB102,11 St & Washington St,HB502,40.736068,-74.029127,40.749985,-74.027150,casual

In [53]:
df_merged.to_csv("Resources/2022-first_6monthJC.csv")

In [54]:
df_merged.to_csv("Resources/2022-first_6monthJC.csv")
df_merged.drop(df_merged.columns[0], axis=1, inplace=True)
df_merged.to_csv("Resources/2022-first_6monthJC.csv",index=False)